### ISSUE TITLE
Regarding data preprocesing for hinglish

### ISSUE THREAD

**Issue by ranjeetiiitn** [SilentFlame/Named-Entity-Recognition#2]
Please can you tell me how you extarcting hinglish sentences from the tweets .i have seprated all the urls numbers and other languages except these english language.
so my humble request to you please reply .

thank you

**Comment by SilentFlame** [comment]
There are libraries which can be used to detect languages in a transliterated form of text.
flow:
1. Convert Hindi (in Devanagari script) text to Latin script, with transliteration.
2. Use pre-trained language identification models to detect language.
3. use a threshold of 'phi' above that ration of ```hindi/total``` you should keep the sentence for the corpus.

**Comment by Rajesh-Behuria** [comment]
where is tagged.csv data set??
plz help me out
